# basic dependabot config to keep Java libs and GitHub actions up-to-date

version: 2
updates:

  # auto-update GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - "nils-s"
    commit-message:
      prefix: "[Dependabot]"
      include: scope
    open-pull-requests-limit: 1

  # auto-update Maven deps
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - "nils-s"
    commit-message:
      prefix: "[Dependabot]"
      include: scope
    open-pull-requests-limit: 1