# basic dependabot config to keep Java libs, GitHub actions, and Docker image up-to-date

version: 2
updates:

  # auto-update GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - "nils-s"
    commit-message:
      include: scope
    open-pull-requests-limit: 1

  # auto-update Maven deps
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - "nils-s"
    commit-message:
      include: scope
    open-pull-requests-limit: 1

  # auto-update Docker base image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - "nils-s"
    commit-message:
      include: scope
    open-pull-requests-limit: 1