name: Build and upload container image

on:
  workflow_dispatch:
    inputs:
      publish-jar:
        type: boolean
        description: Publish jar file to GitHub Packages Maven repository
      publish-image:
        type: boolean
        description: Publish container image to container registry

jobs:
  buildJar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java build environment
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build jar file with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact to GitHub packages repo
        if: ${{ inputs.publish-jar }}
        run: mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy jar to artifacts directory
        run: mkdir artifacts && cp target/*.jar artifacts

      - name: Upload jar as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: artifacts/app.jar

  buildImage:
    needs: buildJar
    runs-on: ubuntu-latest
    env:
      PUBLISH_IMAGE: ${{ inputs.publish-image && (secrets.ACR_IMAGE_PUSH_USER_CLIENT_ID != '') && (secrets.ACR_IMAGE_PUSH_USER_PASSWORD != '') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download application jar file
        uses: actions/download-artifact@v5
        with:
          name: app.jar

      - name: Azure container registry log in
        if: ${{ env.PUBLISH_IMAGE == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: alicecamp22reg.azurecr.io
          username: ${{ secrets.ACR_IMAGE_PUSH_USER_CLIENT_ID }}
          password: ${{ secrets.ACR_IMAGE_PUSH_USER_PASSWORD }}

      - name: Build container image (and upload it, if necessary)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ env.PUBLISH_IMAGE }}
          tags: alicecamp22reg.azurecr.io/nils-s-camp22:latest
